export const promptBank = [
  "cat",
  "dog",
  "book",
  "pen",
  "school",
  "teacher",
  "student",
  "market",
  "computer",
  "phone",
  "table",
  "chair",
  "window",
  "mirror",
  "water",
  "coffee",
  "breakfast",
  "lunch",
  "dinner",
  "family",
  "friend",
  "mother",
  "father",
  "brother",
  "sister",
  "music",
  "movie",
  "travel",
  "ticket",
  "passport",
  "station",
  "engineer",
  "doctor",
  "nurse",
  "project",
  "meeting",
  "future",
  "history",
  "science",
  "language",
  "practice",
  "accent",
  "rhythm",
  "stress",
  "intonation",
  "clarity",
  "confidence",
  "global",
  "culture",
  "business",
  "The weather is pleasant today.",
  "Please speak slowly and clearly.",
  "I would like to improve my pronunciation.",
  "Can you repeat that sentence again?",
  "She bought a cup of hot coffee.",
  "We are planning a trip next month.",
  "The meeting starts at nine o clock.",
  "He reads the newspaper every morning.",
  "They moved to a new apartment.",
  "This project is very important for us.",
  "I need to finish this task today.",
  "Could you help me with this form?",
  "My favorite season is winter.",
  "We should leave before traffic begins.",
  "Please turn off your mobile phone.",
  "He works as a software engineer.",
  "The doctor asked me to rest.",
  "She is learning spoken English online.",
  "I usually wake up at six.",
  "The train arrived ten minutes late.",
  "Let us discuss this after lunch.",
  "Your presentation was clear and simple.",
  "I forgot to bring my wallet.",
  "Can I get a glass of water?",
  "They are building a new bridge.",
  "Our team won the final match.",
  "I enjoy reading books at night.",
  "Please submit the report by Friday.",
  "He called me as soon as he reached home.",
  "She speaks with great confidence.",
  "I am trying to reduce my accent.",
  "The classroom is on the second floor.",
  "We had a productive discussion today.",
  "He answered all the questions correctly.",
  "The internet connection is unstable right now.",
  "Let me know when you are free.",
  "I will join the meeting in five minutes.",
  "This sentence helps train the th sound.",
  "Practice makes your speech more natural.",
  "Focus on stress rhythm and pauses.",
  "Please record your voice one more time.",
  "Listen carefully and imitate the coach.",
  "Your goal is clear speech not speed.",
  "Small improvements lead to big progress.",
  "Try to open your mouth a little more.",
  "Breathe and speak one phrase at a time.",
  "Today we will practice difficult vowels.",
  "Keep your tongue relaxed for this sound.",
  "Say the sentence again with better intonation.",
  "You are doing a great job so far."
];
